CREATE DATABASE FSPIZZARIA;

USE FSPIZZARIA;

CREATE TABLE CATEGORIAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL 
	,DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE PIZZARIAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,ENDERECO VARCHAR(255) NOT NULL UNIQUE 
	,VEGANA BIT NOT NULL 
	,TELEFONE VARCHAR(10) NOT NULL
	,ID_CATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(ID)
);

CREATE TABLE USUARIO(
	ID INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR(255) NOT NULL 
);
